import CrewCreateWindow from './CrewCreateWindow';
import HolodeckConsole from './HolodeckConsole';
import MedicalChartWindow from './MedicalChartWindow';
import PersonnelDossier from './PersonnelDossier';
import ReplicatorConsole from './ReplicatorConsole';
import SystemsCompartmentWindow from './SystemsCompartmentWindow';
import TransporterConsole from './TransporterConsole';

function AppOverlays(props) {
  const {
    activeWorkspace,
    closeHolodeckConsole,
    closeReplicatorConsole,
    closeTransporterConsole,
    crewCreateForm,
    departments,
    dossierRef,
    dossierTab,
    formState,
    handleCrewCreateChange,
    handleCrewCreateSubmit,
    handleEpisodeChange,
    handleFormChange,
    handleHolodeckEpisodeChange,
    handleHolodeckLogChange,
    handleHolodeckLogSubmit,
    handleHolodeckProgramChange,
    handleHolodeckProgramSubmit,
    handleHolodeckSeasonChange,
    handleMedicalProfileChange,
    handleMedicalProfileSubmit,
    handleMedicalRecordChange,
    handleMedicalRecordEpisodeChange,
    handleMedicalRecordSeasonChange,
    handleMedicalRecordSubmit,
    handleReplicatorEpisodeChange,
    handleReplicatorLogChange,
    handleReplicatorLogSubmit,
    handleReplicatorPatternChange,
    handleReplicatorPatternSubmit,
    handleReplicatorSeasonChange,
    handleSeasonChange,
    handleSubmit,
    handleTransporterChange,
    handleTransporterEpisodeChange,
    handleTransporterLogSubmit,
    handleTransporterPassengerChange,
    handleTransporterSeasonChange,
    holodeckLogForm,
    holodeckProgramForm,
    holodeckPrograms,
    holodeckTab,
    holodeckUnits,
    loadingDetail,
    loadingMedicalDetail,
    loadingSystemDetail,
    medicalProfileForm,
    medicalRecordForm,
    medicalTab,
    pagedReplicatorPatterns,
    recentActions,
    replicatorCrewOptions,
    replicatorLogForm,
    replicatorPatternForm,
    replicatorPatterns,
    replicatorTab,
    replicatorUnits,
    safeReplicatorPatternPage,
    selectedCompartment,
    selectedCrew,
    selectedDepartmentName,
    selectedHolodeckCrew,
    selectedHolodeckLog,
    selectedHolodeckProgram,
    selectedHolodeckSeasonGuide,
    selectedHolodeckUnit,
    selectedMedicalChart,
    selectedMedicalSeasonGuide,
    selectedReplicatorCrew,
    selectedReplicatorLog,
    selectedReplicatorPattern,
    selectedReplicatorSeasonGuide,
    selectedReplicatorUnit,
    selectedSeasonGuide,
    selectedTransporterEvent,
    selectedTransporterLocation,
    selectedTransporterOperator,
    selectedTransporterPassengers,
    selectedTransporterSeasonGuide,
    selectedTransporterUnit,
    setDossierTab,
    setHolodeckTab,
    setMedicalTab,
    setReplicatorLogForm,
    setReplicatorPatternPage,
    setReplicatorTab,
    setSelectedCompartmentId,
    setSelectedCrewId,
    setSelectedMedicalCrewId,
    setShowCrewCreate,
    setTransporterLogForm,
    setTransporterTab,
    showCrewCreate,
    showHolodeckConsole,
    showReplicatorConsole,
    showTransporterConsole,
    submitting,
    submittingCrewCreate,
    submittingHolodeck,
    submittingHolodeckProgram,
    submittingMedical,
    submittingReplicator,
    submittingReplicatorPattern,
    submittingTransporter,
    totalReplicatorPatternPages,
    transporterLocations,
    transporterLogForm,
    transporterTab,
    transporterUnits,
  } = props;

  return (
    <>
      <MedicalChartWindow
        activeWorkspace={activeWorkspace}
        closeChart={() => setSelectedMedicalCrewId(null)}
        dossierRef={dossierRef}
        handleMedicalProfileChange={handleMedicalProfileChange}
        handleMedicalProfileSubmit={handleMedicalProfileSubmit}
        handleMedicalRecordChange={handleMedicalRecordChange}
        handleMedicalRecordEpisodeChange={handleMedicalRecordEpisodeChange}
        handleMedicalRecordSeasonChange={handleMedicalRecordSeasonChange}
        handleMedicalRecordSubmit={handleMedicalRecordSubmit}
        loadingMedicalDetail={loadingMedicalDetail}
        medicalProfileForm={medicalProfileForm}
        medicalRecordForm={medicalRecordForm}
        medicalTab={medicalTab}
        selectedMedicalChart={selectedMedicalChart}
        selectedMedicalSeasonGuide={selectedMedicalSeasonGuide}
        setMedicalTab={setMedicalTab}
        submittingMedical={submittingMedical}
      />
      <PersonnelDossier
        departments={departments}
        dossierRef={dossierRef}
        dossierTab={dossierTab}
        formState={formState}
        handleEpisodeChange={handleEpisodeChange}
        handleFormChange={handleFormChange}
        handleSeasonChange={handleSeasonChange}
        handleSubmit={handleSubmit}
        loadingDetail={loadingDetail}
        recentActions={recentActions}
        selectedCrew={selectedCrew}
        selectedDepartmentName={selectedDepartmentName}
        selectedSeasonGuide={selectedSeasonGuide}
        setDossierTab={setDossierTab}
        setSelectedCrewId={setSelectedCrewId}
        submitting={submitting}
      />
      <CrewCreateWindow
        activeWorkspace={activeWorkspace}
        crewCreateForm={crewCreateForm}
        departments={departments}
        handleCrewCreateChange={handleCrewCreateChange}
        handleCrewCreateSubmit={handleCrewCreateSubmit}
        setShowCrewCreate={setShowCrewCreate}
        showCrewCreate={showCrewCreate}
        submittingCrewCreate={submittingCrewCreate}
      />
      <ReplicatorConsole
        activeWorkspace={activeWorkspace}
        closeReplicatorConsole={closeReplicatorConsole}
        dossierRef={dossierRef}
        handleReplicatorEpisodeChange={handleReplicatorEpisodeChange}
        handleReplicatorLogChange={handleReplicatorLogChange}
        handleReplicatorLogSubmit={handleReplicatorLogSubmit}
        handleReplicatorPatternChange={handleReplicatorPatternChange}
        handleReplicatorPatternSubmit={handleReplicatorPatternSubmit}
        handleReplicatorSeasonChange={handleReplicatorSeasonChange}
        pagedReplicatorPatterns={pagedReplicatorPatterns}
        replicatorCrewOptions={replicatorCrewOptions}
        replicatorLogForm={replicatorLogForm}
        replicatorPatternForm={replicatorPatternForm}
        replicatorPatterns={replicatorPatterns}
        replicatorTab={replicatorTab}
        replicatorUnits={replicatorUnits}
        selectedReplicatorCrew={selectedReplicatorCrew}
        selectedReplicatorLog={selectedReplicatorLog}
        selectedReplicatorPattern={selectedReplicatorPattern}
        selectedReplicatorSeasonGuide={selectedReplicatorSeasonGuide}
        selectedReplicatorUnit={selectedReplicatorUnit}
        setReplicatorPatternPage={setReplicatorPatternPage}
        setReplicatorTab={setReplicatorTab}
        setReplicatorLogForm={setReplicatorLogForm}
        showReplicatorConsole={showReplicatorConsole}
        submittingReplicator={submittingReplicator}
        submittingReplicatorPattern={submittingReplicatorPattern}
        safeReplicatorPatternPage={safeReplicatorPatternPage}
        totalReplicatorPatternPages={totalReplicatorPatternPages}
      />
      <TransporterConsole
        activeWorkspace={activeWorkspace}
        closeTransporterConsole={closeTransporterConsole}
        dossierRef={dossierRef}
        handleTransporterChange={handleTransporterChange}
        handleTransporterEpisodeChange={handleTransporterEpisodeChange}
        handleTransporterLogSubmit={handleTransporterLogSubmit}
        handleTransporterPassengerChange={handleTransporterPassengerChange}
        handleTransporterSeasonChange={handleTransporterSeasonChange}
        replicatorCrewOptions={replicatorCrewOptions}
        selectedTransporterEvent={selectedTransporterEvent}
        selectedTransporterLocation={selectedTransporterLocation}
        selectedTransporterOperator={selectedTransporterOperator}
        selectedTransporterPassengers={selectedTransporterPassengers}
        selectedTransporterSeasonGuide={selectedTransporterSeasonGuide}
        selectedTransporterUnit={selectedTransporterUnit}
        setTransporterLogForm={setTransporterLogForm}
        setTransporterTab={setTransporterTab}
        showTransporterConsole={showTransporterConsole}
        submittingTransporter={submittingTransporter}
        transporterLocations={transporterLocations}
        transporterLogForm={transporterLogForm}
        transporterTab={transporterTab}
        transporterUnits={transporterUnits}
      />
      <HolodeckConsole
        activeWorkspace={activeWorkspace}
        closeHolodeckConsole={closeHolodeckConsole}
        dossierRef={dossierRef}
        handleHolodeckEpisodeChange={handleHolodeckEpisodeChange}
        handleHolodeckLogChange={handleHolodeckLogChange}
        handleHolodeckLogSubmit={handleHolodeckLogSubmit}
        handleHolodeckProgramChange={handleHolodeckProgramChange}
        handleHolodeckProgramSubmit={handleHolodeckProgramSubmit}
        handleHolodeckSeasonChange={handleHolodeckSeasonChange}
        holodeckLogForm={holodeckLogForm}
        holodeckProgramForm={holodeckProgramForm}
        holodeckPrograms={holodeckPrograms}
        holodeckTab={holodeckTab}
        holodeckUnits={holodeckUnits}
        replicatorCrewOptions={replicatorCrewOptions}
        selectedHolodeckCrew={selectedHolodeckCrew}
        selectedHolodeckLog={selectedHolodeckLog}
        selectedHolodeckProgram={selectedHolodeckProgram}
        selectedHolodeckSeasonGuide={selectedHolodeckSeasonGuide}
        selectedHolodeckUnit={selectedHolodeckUnit}
        setHolodeckTab={setHolodeckTab}
        showHolodeckConsole={showHolodeckConsole}
        submittingHolodeck={submittingHolodeck}
        submittingHolodeckProgram={submittingHolodeckProgram}
      />
      <SystemsCompartmentWindow
        activeWorkspace={activeWorkspace}
        closeWindow={() => setSelectedCompartmentId(null)}
        dossierRef={dossierRef}
        loadingSystemDetail={loadingSystemDetail}
        selectedCompartment={selectedCompartment}
      />
    </>
  );
}

export default AppOverlays;
